# fly.toml app configuration file generated for n8n-relay on 2025-06-16T17:56:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-relay'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
